language: python
python:
- '3.6'

install: sudo ./.ci/install_dependencies.sh $HOME/tools

before_script:
- export PATH=$HOME/tools:$HOME/tools/vcflib/bin:$PATH

script:
- pytest

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PWD
  on:
    tags: true
